### ISSUE TITLE
Linking error: libipmf.so.0 is corrupted and unreadable

### ISSUE THREAD

**Issue by OrdiTader** [nerscadmin/IPM#12] opened 2016-03-13 15:24 UTC
Dear admin,

I have the error during linking the IPM project:
/bin/sh ../libtool  --tag=FC   --mode=link mpif90  -mcpu=elbrus-4c -fuse-glibc  -mcpu=elbrus-4c -fuse-glibc -L/usr/lib64 -o libipmf.la -rpath /home/ordi/inst/IPM/lib libipmf_la-mpi_fortran.lo libipmf_la-GEN.wrapper_mpif.lo
libtool: link: mpif90 -shared   .libs/libipmf_la-mpi_fortran.o .libs/libipmf_la-GEN.wrapper_mpif.o    -L/usr/lib64 -L/opt/mpich2-1.1.1p1/lib -L/opt/mcst/lcc-home/1.19.21/e2k-4c-linux/lib/ptr64 -lmpichf90 -lmpich -lopa -lpthread -lrt /usr/lib/libfcc.so -lm -lmvec -lgcc -lgcc_eh -lc  -mcpu=elbrus-4c -mcpu=elbrus-4c   -soname libipmf.so.0 -o .libs/libipmf.so.0.0.0
lcc: error: file or directory "libipmf.so.0" is corrupted and unreadable

./configure --prefix=/home/ordi/inst/IPM/  FC=gfortran  --with-gnu-ld

I have mpich2: 1.1.1p1 and gcc version 4.4.0 compatible.

What am I doing wrong? I've tried 2.0.3, 2.04 and 2.0.5 releases.
Thank you!

Best regards,
ordi

**Comment by swfrench** [comment] 2016-03-14 03:32
Hi Ordi,

Neat to see that you're building IPM for an Elbrus!

I've tested IPM 2.0.5 with mpich2 1.1.1p1 on x86_64 under gcc and I don't see this issue. Thus, I suspect it might be specific to the lcc-based toolchain you're using.

Are you cross-compiling for the Elbrus or is it the host system? If cross, are you certain that gfortran is not accidentally targeting the host at some step, resulting in seemingly corrupt object files? (corrupt according to lcc)

Another thought: Does your mpich2-on-lcc build support static linking? If so, I'd recommend trying to build a static-only IPM install (re-run `configure` with `--disable-shared`) as a starting point.

Cheers,
Scott

**Comment by OrdiTader** [comment] 2016-03-14 11:35
Hi Scott!!
Thank you so much for your fast reply! You helped me a lot. Yes, Elbrus is the host system. 
The "--disable-shared" option worked, I've compiled IPM (without PAPI)!

**Comment by swfrench** [comment] 2016-03-15 02:10
Hi Ordi,

Thanks for the update - glad to hear that the static build seems to have worked!

With that in mind, does static linking seem like a solution that could work for your use case? The reason I ask is that it is unlikely I would be able to reproduce or troubleshoot the issue in depth without access to an Elbrus and the lcc-based toolchain.

If the static-linking solution is suitable for you, I am tempted to close this issue for now (while noting the static linking workaround).

Cheers,
Scott

**Comment by OrdiTader** [comment] 2016-03-15 11:55
Dear Scott,
Yes, static linking is ok for my test case! 
Thank you very much for your help and for the IPM utility!

**Comment by swfrench** [comment] 2016-03-17 02:17
Hi Ordi,

Great! Many thanks for your reply. I will close the issue and note that we can use this as a workaround in the future for similar cases.

Cheers,
Scott

**Closed by swfrench** 2016-03-17 02:17 UTC
